<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $report['label'] }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #111; line-height: 1.45; padding: 28px; }
        .header { border-bottom: 2px solid #111; padding-bottom: 12px; margin-bottom: 18px; }
        .header-table { width: 100%; border-collapse: collapse; }
        .header-table td { vertical-align: middle; }
        .header-logo { width: 22%; text-align: center; }
        .header-logo img { max-height: 64px; max-width: 110px; }
        .header-center { width: 56%; text-align: center; padding: 0 6px; }
        .header-org { font-size: 8px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.3px; }
        .header-title { font-size: 16px; font-weight: bold; margin: 4px 0; }
        .header-doc { font-size: 11px; font-weight: bold; text-transform: uppercase; margin-top: 6px; padding-top: 5px; border-top: 1px solid #111; }
        .meta { margin-bottom: 14px; }
        .meta td { padding: 2px 0; }
        .meta .label { color: #555; width: 120px; }
        .section { margin-bottom: 16px; }
        .section-title { font-size: 11px; font-weight: bold; text-transform: uppercase; border-bottom: 1px solid #111; padding-bottom: 3px; margin-bottom: 8px; }
        table.data { width: 100%; border-collapse: collapse; margin-top: 4px; }
        table.data th, table.data td { border: 1px solid #ccc; padding: 5px 6px; text-align: left; vertical-align: top; }
        table.data th { background: #eef2f7; font-size: 10px; text-transform: uppercase; }
        .note { padding: 10px; border: 1px solid #c7d2fe; background: #eff6ff; margin-bottom: 12px; }
        .footer { margin-top: 22px; border-top: 1px solid #ccc; padding-top: 8px; font-size: 9px; color: #666; }
        .right { text-align: right; }
        .muted { color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <table class="header-table">
            <tr>
                <td class="header-logo">
                    @if (!empty($bcc_logo))
                        <img src="{{ $bcc_logo }}" alt="BCC">
                    @endif
                </td>
                <td class="header-center">
                    <div class="header-org">Baao Community College</div>
                    <div class="header-title">{{ $app_name ?? 'SSCEVS' }}</div>
                    <div class="header-doc">{{ $report['label'] }}</div>
                </td>
                <td class="header-logo">
                    @if (!empty($ssc_logo))
                        <img src="{{ $ssc_logo }}" alt="SSC">
                    @endif
                </td>
            </tr>
        </table>
    </div>

    <table class="meta">
        <tr>
            <td class="label">Election</td>
            <td><strong>{{ $report['election']['title'] }}</strong></td>
        </tr>
        <tr>
            <td class="label">Voting period</td>
            <td>{{ $report['election']['voting_period'] }}</td>
        </tr>
        <tr>
            <td class="label">Status</td>
            <td>{{ $report['election']['status_label'] }} ({{ $report['election']['voting_phase'] }})</td>
        </tr>
        <tr>
            <td class="label">Generated</td>
            <td>{{ $report['generated_at'] }}</td>
        </tr>
        @if (!empty($report['date_from']) || !empty($report['date_to']))
            <tr>
                <td class="label">Date filter</td>
                <td>
                    {{ $report['date_from'] ?? '—' }}
                    to
                    {{ $report['date_to'] ?? '—' }}
                </td>
            </tr>
        @endif
    </table>

    @yield('content')

    <div class="footer">
        Generated by {{ $app_name ?? 'SSCEVS' }} · {{ $report['generated_at'] }} · For official election records
    </div>
</body>
</html>
